class Helper:

    def __init__(self):
        self.sector_dict = {}
        self.fill_sector_dict()

    def get_dictionary(self):
        return self.sector_dict

    def fill_sector_dict(self):
        self.sector_dict["Agro en visserij"] = "3A5579"
        self.sector_dict["Amusementsindustrie"] = "3A5711"
        self.sector_dict["Apperatuur"] = "3A5777"
        self.sector_dict["Automotive"] = "3A5999"
        self.sector_dict["Beveiligingsindustrie"] = "3A5779"
        self.sector_dict["Binnenvaart"] = "3A6057"
        self.sector_dict["Biogas en groen gas"] = "3A5819"
        self.sector_dict["Biologische landbouw"] = "3A5585"
        self.sector_dict["Biomassa"] = "3A5805"
        self.sector_dict["Bouw"] = "3A5621"
        self.sector_dict["Bouw en infrastructuur"] = "3A5619"
        self.sector_dict["Bouwmaterialen"] = "3A5625"
        self.sector_dict["Civiele techniek"] = "3A5627"
        self.sector_dict["Consultancy"] = "3A5743"
        self.sector_dict["Consumentengoederen"] = "3A5681"
        self.sector_dict["Consumentengoederen en detailhandel"] = "3A5673"
        self.sector_dict["Creatieve industrie"] = "3A5709"
        self.sector_dict["Deltatechnologie"] = "3A6103"
        self.sector_dict["Dienstsector"] = "3A5735"
        self.sector_dict["Elektronica-industrie"] = "3A5775"
        self.sector_dict["Energieopwekking"] = "3A5815"
        self.sector_dict["Energiesector"] = "3A5803"
        self.sector_dict["Farmaceutische producten"] = "3A5879"
        self.sector_dict["Geothermie"] = "3A5817"
        self.sector_dict["Gezondheidszorg"]  = "3A5881"
        self.sector_dict["Huishoudeijke apparatuur"] = "3A5697"
        self.sector_dict["ICT"] = "3A5845"
        self.sector_dict["Informatietechnologie"] = "3A5849"
        self.sector_dict["Infrastructuur"] = "3A5633"
        self.sector_dict["Instrumenten"] = "3A5787"
        self.sector_dict["Intensieve veehouderij"] = "3A5597"
        self.sector_dict["Landbouw"] = "3A5587"
        self.sector_dict["Lucht- en ruimtevaarttechnologie"] = "3A6003"
        self.sector_dict["Luchtzuivering"] = "3A5923"
        self.sector_dict["Media"] = "3A5725"
        self.sector_dict["Medische apparatenindustrie"] = "3A5889"
        self.sector_dict["Medische hulpmiddelen"] = "3A5891"
        self.sector_dict["Medische sector"] = "3A5875"
        self.sector_dict["Micro-en nanotechnologie"] = "3A5789"
        self.sector_dict["Micro-elektronica"] = "3A5795"
        self.sector_dict["Milieusector"] = "3A5913"
        self.sector_dict["Multimodaal vervoer"] = "3A6033"
        self.sector_dict["Nieuwe media en gaming"] = "3A5731"
        self.sector_dict["Olie en gas"] = "3A5825"
        self.sector_dict["Onderhoudsbedrijven"] = "3A5639"
        self.sector_dict["Openbaar vervoer"] = "3A6035"
        self.sector_dict["Overheid"] = "3A5955"
        self.sector_dict["Robotica"] = "3A5799"
        self.sector_dict["Semioverheid"] = "3A5981"
        self.sector_dict["Sensortechnologie"] = "3A5801"
        self.sector_dict["Simulatie en serious gaming"] = "3A5733"
        self.sector_dict["Software"] = "3A5851"
        self.sector_dict["Sport"]  = "3A5993"
        self.sector_dict["Toerisme recreatie en horeca"] = "3A5985"
        self.sector_dict["Transportmiddelenindustrie"] = "3A5997"
        self.sector_dict["Tuinbouw"] = "3A5589"
        self.sector_dict["Tweewielers"] = "3A6023"
        self.sector_dict["Veeteelt"] = "3A5595"
        self.sector_dict["Vervoer en logistiek"] = "3A6027"
        self.sector_dict["Vervoer over water"] = "3A6055"
        self.sector_dict["Vliegtuigbouw"] = "3A6009"
        self.sector_dict["Voedings-en genotmiddelen"] = "3A6065"
        self.sector_dict["Voedingsmiddelen"] = "3A6081"
        self.sector_dict["Waste-to-energy"] = "3A5829"
        self.sector_dict["Waterbeheer"] = "3A6107"
        self.sector_dict["Waterbouw"] = "3A6109"
        self.sector_dict["Waterkracht"] = "3A5831"
        self.sector_dict["Watersector"] = "3A6101"
        self.sector_dict["Watertechnologie"] = "3A6111"
        self.sector_dict["Waterzuivering"] = "3A6115"
        self.sector_dict["Wegwerken"] = "3A5631"
        self.sector_dict["Windenergie"] = "3A5833"
        self.sector_dict["Woningbouw"] = "3A5647"
        self.sector_dict["Zonne-energie"] = "3A5835"
